---
name: "Post-Run Action"
description: "A simple GitHub action that enables running post-run tasks, once a workflow job has ended."

inputs:
  run:
    description: "A command that needs to be run."
    required: true
    default: echo "This is a post-action command..."
  cwd:
    description: "A working directory from which the command needs to be run."
    required: false
  always:
    description: "Always run, even if the job fails."
    required: false
    default: "false"

runs:
  using: node20
  main: main.js
  post: post.js
  post-if: success() || ${{ inputs.always == 'true' }}
