---
name: "cargo-binstall"
description: "A GitHub action to download and install binaries using `cargo-binstall`."
author: "Ian Ker-Seymer"
branding:
  icon: "download-cloud"
  color: "gray-dark"
inputs:
  crate:
    description: "The crate to install."
    required: true
  version:
    description: "The version to install."
    required: true
  install-path:
    description: "The path to install the crate to."
    required: false
    default: default
  strategies:
    description: "The strategies to use."
    required: false
    default: default
outputs:
  status:
    description: "The status of the installation."
    value: ${{ steps.install.outputs.status }}
runs:
  using: "composite"
  steps:
    - name: Install
      id: install
      shell: bash
      run: |
        : Install
        echo "::group::Install crate"

        args = "--no-confirm --force --secure"

        if [ "${{ inputs.install-path }}" != "default" ]; then
          args="$args --install-path ${{ inputs.install-path }}"
        fi

        if [ "${{ inputs.strategies }}" != "default" ]; then
          args="$args --strategies ${{ inputs.strategies }}"
        fi

        $GITHUB_ACTION_PATH/cargo-binstall ${{ inputs.crate }} --version ${{ inputs.version }} $args
        echo "::endgroup::"
        echo "status=success" >> $GITHUB_OUTPUT
