# Add to path in cross platform way
def normalize_os_path(path)
  return path unless ENV.fetch("OS").match?(/windows/i)

  path.gsub("/", "\\")
end

desc "Build cargo cache and save the binary to $OUT_DIR"
task 'cargo-cache' do
  outdir = ENV.fetch('OUT_DIR', "tmp/prebuilt-local/bin")
  outdir = normalize_os_path(outdir)
  root = File.dirname(outdir)
  version = ENV["VERSION"] || "0.8.3"

  puts "🧱 Building cargo-cache #{version} and saving to #{outdir}"

  sh <<~SH
    cargo install --features ci-autoclean cargo-cache --root #{root} --version #{version}
  SH

  if File.exist?(normalize_os_path(File.join(outdir, "cargo-cache")))
    puts "✅ cargo-cache binary built and saved to #{outdir}"
  else
    abort "❌ cargo-cache binary not found in #{outdir}"
  end
end
